### PR TITLE
chore::> `JsonStore` library logic impl

### PR DESCRIPTION
**Pull request by PsychoPunkSage**
`JsonStore` library complete with 100% coverage <forge coverage>

```js
| File                                                                                       | % Lines          | % Statements     | % Branches     | % Funcs         |
|--------------------------------------------------------------------------------------------|------------------|------------------|----------------|-----------------|
| contracts/utils/JsonStore.sol                                                              | 100.00% (27/27)  | 100.00% (38/38)  | 100.00% (9/9)  | 100.00% (11/11) |
```

### CODE REVIEW

**Comment by PsychoPunkSage** [comment]
## Impl
Library doesn't support `Var Data structure` like `maps` or `arrays`
so to deal with storage I used
```js
struct JsonData {
       string jsonBlob;
       bool exists;
       address owner;
}
```
* Is it OK??
* Cause this will require us to change the fn signature across the repo wherever `JsonStore` is used


## Test
All the commented tests are failing....
I'm not sure but I think the problem is related to testing `reverts`
For ex.: **testSetWithoutPrepaidSlots**
for this code
```js
function testSetWithoutPrepaidSlots() public {
        vm.startPrank(otherUser); // Switch to unpaid user
        store.set(TEST_SLOT, TEST_JSON);
        vm.stopPrank();
   }
```

error == `[FAIL. Reason: JsonStore__InsufficientPrepaidSlots()] testSetWithoutPrepaidSlots() (gas: 191434)`

for this code
```
function testSetWithoutPrepaidSlots() public {
        vm.startPrank(otherUser); // Switch to unpaid user
        vm.expectRevert();
        store.set(TEST_SLOT, TEST_JSON);
        vm.stopPrank();
    }
```
error == `[FAIL. Reason: next call did not revert as expected] testSetWithoutPrepaidSlots() (gas: 105265)`

Since I already know it should revert, yet it is not reverting....

**Comment by pablin-dev** [comment]
I think ```js
struct JsonData {
       string jsonBlob;
       bool exists;
       address owner;
}
``` is correct. You store the object as raw data, maybe compressed if it is too big to save space. On runtime and memory you `transform` or `serialize/deserealize` this raw data into what ever you need. look at [Foundry write-json](https://book.getfoundry.sh/cheatcodes/write-json) and [serialize-json](https://book.getfoundry.sh/cheatcodes/serialize-json) `The idea is that the user serializes the values of the JSON file and finally writes that object to a file.`

**Comment by pablin-dev** [comment]
```
function testSetWithoutPrepaidSlots() public {
        vm.startPrank(otherUser); // Switch to unpaid user
        vm.expectRevert();
        store.set(TEST_SLOT, TEST_JSON);
        vm.stopPrank();
    }
``` 

Since 
`function set(Store storage self, bytes32 _slot, string memory _jsonBlob) internal returns (bool) {` is defined as `internal` (internal method and not `public`) this makes a `JUMP`, not a `CALL` so when you execute `store.set(TEST_SLOT, TEST_JSON);` its JUMP to that code and `never get back` since it not a `CALL` with a return (this `vm.stopPrank();` is never executed, it finish on `set`.

Changing the scope of `set` from `internal` to `external` fix this.

**Comment by PsychoPunkSage** [comment]
@pablin-dev 
This PR is ready to be merged....

Please have a look at it...

**Pull request merged**
