### PR TITLE
chore::> `JsonParser` is ready

### PR DESCRIPTION
**Pull request by PsychoPunkSage**
The `contracts/utils/JsonParser.sol` is ready and properly tested

Codecov stats::>
```
| File                                                                   | % Lines           | % Statements      | % Branches      | % Funcs         |
| contracts/utils/JsonParser.sol                                         | 92.81% (155/167)  | 94.23% (196/208)  | 86.67% (26/30)  | 100.00% (22/22) |
```

## Issue:
The tests suggest `JsonParser.sol` to be quite expensive

Here is the stats
```js
Ran 13 tests for test/utils/JsonParser.t.sol:JsonParserTest
[PASS] testComplexJson() (gas: 342834)
[PASS] testEmptyArray() (gas: 102340)
[PASS] testEmptyObject() (gas: 102294)
[PASS] testGetBytes() (gas: 12843)
[PASS] testInvalidJson() (gas: 106085)
[PASS] testMemoryLimit() (gas: 21531)
[PASS] testNestedJson() (gas: 166389)
[PASS] testPrimitiveTypes() (gas: 153823)
[PASS] testStringUtilities() (gas: 59208)
[PASS] testValidEscapeSequences() (gas: 119127)
[PASS] testValidJsonArray() (gas: 129979)
[PASS] testValidJsonObject() (gas: 127912)
[PASS] testWhitespaceHandling() (gas: 116514)
Suite result: ok. 13 passed; 0 failed; 0 skipped; finished in 17.08ms (74.33ms CPU time)
```

### CODE REVIEW

**Comment by PsychoPunkSage** [comment]
@pablin-dev Please review the PR :)

**Comment by pablin-dev** [comment]
LGTM! Nice work! working with libraries is a really challenge. 

Some suggestions, we can do this later. **For me is ready to merge.**

- Consider adding documentation using [natspec](https://docs.soliditylang.org/en/latest/natspec-format.html#natspec)
- API Design:
  - Consider using "_" for private functions of the API to explicit tell the user for internal use.
  - Consider adding main API "entrypoint" (JsonParser.parse()).
  - Note: Lots of parsing transformation could be used on another functions, we could use them outside this API.

**Review by pablin-dev — APPROVED** [review]
LGTM! Ready to merge.

**Comment by PsychoPunkSage** [comment]
Ok @pablin-dev  thanks
I will merge this PR...

I will also create an issue for these Points... so that we can keep track of it

> LGTM! Nice work! working with libraries is a really challenge.
> 
> Some suggestions, we can do this later. **For me is ready to merge.**
> 
> * Consider adding documentation using [natspec](https://docs.soliditylang.org/en/latest/natspec-format.html#natspec)
> * API Design:
>   
>   * Consider using "_" for private functions of the API to explicit tell the user for internal use.
>   * Consider adding main API "entrypoint" (JsonParser.parse()).
>   * Note: Lots of parsing transformation could be used on another functions, we could use them outside this API.

**Comment by PsychoPunkSage** [comment]
@pablin-dev  #3

**Pull request merged**
