### PR TITLE
fix: Issue templates

### PR DESCRIPTION
**Pull request by pablin-dev**

### CODE REVIEW

**Review by PsychoPunkSage — CHANGES_REQUESTED** [review]
In `PULL_REQUEST_TEMPLATE.MD`
We can add a section for `ISSUES` the PR will be fixing/closing/addressing

**Comment by pablin-dev** [comment]
> In `PULL_REQUEST_TEMPLATE.MD` We can add a section for `ISSUES` the PR will be fixing/closing/addressing

Done.

**Review by pablin-dev — COMMENTED** [review]
Ready for review.

**Review by PsychoPunkSage — APPROVED** [review]

**Comment by PsychoPunkSage** [comment]
GTG....
We can merge

**Pull request merged**
